version: '3.7'

services:
  app:
    container_name: aapl-ui
    build:
      context: .
      target: development
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://localhost:3001

      